<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_abc def xyz_trash icon</name>
   <tag></tag>
   <elementGuidId>49c1b552-505a-43a3-9034-ab3605c435a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr.active.warning > td.right.aligned.collapsing.options-buttons-container > button.ui.button.icon > i.trash.icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content']/div/div[2]/div/table/tbody/tr[4]/td[8]/button[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a6e41f99-458d-435e-8b41-42544b473d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>096d3bb0-31ad-4ab7-af52-865ec6f524f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>trash icon</value>
      <webElementGuid>2fe50658-5d47-456c-8d84-2126c60826db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;ui fluid container&quot;]/div[@class=&quot;ui fluid container main-content&quot;]/div[@class=&quot;table-wrapper&quot;]/table[@class=&quot;ui celled definition sortable striped table custom-grid&quot;]/tbody[1]/tr[@class=&quot;active warning&quot;]/td[@class=&quot;right aligned collapsing options-buttons-container&quot;]/button[@class=&quot;ui button icon&quot;]/i[@class=&quot;trash icon&quot;]</value>
      <webElementGuid>999695ce-192b-4994-a80c-c321145c5146</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/div[2]/div/table/tbody/tr[4]/td[8]/button[2]/i</value>
      <webElementGuid>e504b641-452f-4173-8a7d-f4ae21075714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[8]/button[2]/i</value>
      <webElementGuid>64396b54-242e-4d75-8127-1f7ee93c9d7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
