<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Create_edit icon</name>
   <tag></tag>
   <elementGuidId>2e962ed0-b4de-4f8b-b215-0797f74d8a92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dashboard-toolbar']/div[2]/div/a/button/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.edit.icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>768d6b45-347b-4229-9990-e2d08dc879c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>36aa6953-6dcf-4de9-bedb-cd758fe986d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>edit icon</value>
      <webElementGuid>2d83fa51-25f8-40f3-aee7-390a20452aec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard-toolbar&quot;)/div[@class=&quot;ui right secondary pointing menu toolbar-container&quot;]/div[@class=&quot;item&quot;]/a[1]/button[@class=&quot;ui linkedin button&quot;]/i[@class=&quot;edit icon&quot;]</value>
      <webElementGuid>a489e48a-a746-4c1d-bb64-df15e44c665b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard-toolbar']/div[2]/div/a/button/i</value>
      <webElementGuid>df041ea8-0114-415e-9389-cd73d642f14b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/button/i</value>
      <webElementGuid>504a3e06-9a10-4451-8f79-9d9dacc66077</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
