<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label (1)</name>
   <tag></tag>
   <elementGuidId>21386a5d-763c-41d7-abaf-5e70a0f6d383</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ui.fitted.read-only.checkbox > label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content']/div/div[2]/div/table/tbody/tr/td/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>d95213fe-2ef5-484e-ab01-16d2acae4191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;ui fluid container&quot;]/div[@class=&quot;ui fluid container main-content&quot;]/div[@class=&quot;table-wrapper&quot;]/table[@class=&quot;ui celled definition sortable striped table custom-grid&quot;]/tbody[1]/tr[@class=&quot;active&quot;]/td[1]/div[@class=&quot;ui fitted read-only checkbox&quot;]/label[1]</value>
      <webElementGuid>0d6b569d-ee53-41f9-a51b-8b405f9197fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/div[2]/div/table/tbody/tr/td/div/label</value>
      <webElementGuid>060ea7eb-ef1e-4869-871a-16d57c78c811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/label</value>
      <webElementGuid>e4dcb0da-cdae-4ffa-8710-cda036d7c117</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
