<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>circle__colored</name>
   <tag></tag>
   <elementGuidId>13cf29ef-0a3c-4a80-8cac-ccbe75ca7f26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//circle[@id = 'colored']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#colored</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>circle</value>
      <webElementGuid>4c3bc7fd-0861-4007-9635-4b2f2e99f52f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>colored</value>
      <webElementGuid>f4955f08-7965-4de3-a65b-27fb7d5ed43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>#000</value>
      <webElementGuid>4735b940-3c1a-42d1-9617-4ad577ac1c61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cx</name>
      <type>Main</type>
      <value>77</value>
      <webElementGuid>c0220de7-afbf-49b9-b685-9c9c817f79e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cy</name>
      <type>Main</type>
      <value>77</value>
      <webElementGuid>4c15233d-8e2e-46e1-99e9-e5251381e60d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>r</name>
      <type>Main</type>
      <value>72</value>
      <webElementGuid>98bf7577-4f3b-4f5e-b275-6d8a240e33e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;colored&quot;)</value>
      <webElementGuid>37d8460b-8495-497b-bdfb-272597feec57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//circle[@id = 'colored']</value>
      <webElementGuid>7bea2d7f-9c7d-45a2-b205-0bea47f1b410</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
