<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__number (2)</name>
   <tag></tag>
   <elementGuidId>a5cb62fe-11d3-465e-868a-82c977bb4cfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#number</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c749b31f-13d7-431f-9284-a24cce98ec66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>42665f50-94ff-4a2d-ac17-c9d363b00fb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5135c57d-2bbc-4aba-97c1-e809464dad5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Result ?</value>
      <webElementGuid>61b36132-a50b-4e99-939d-39d12476260b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;number&quot;)</value>
      <webElementGuid>8ade59c4-7289-4384-bf69-6abea0a0cd5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='number']</value>
      <webElementGuid>2f4f65ed-39f8-490c-859d-e1918ea60d06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/section/div/div/div[2]/div/div/div/div/div/div/div/div/div/div[2]/div/input</value>
      <webElementGuid>3742c832-4d22-47ad-b7d1-eb64b8be546d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>9922e56b-6473-4ff2-a0fd-5d8c79c9172c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'number' and @type = 'text' and @placeholder = 'Result ?']</value>
      <webElementGuid>92baebf5-994f-4864-8dc5-5c06d203e32f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
