<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Instant Demo_business_name</name>
   <tag></tag>
   <elementGuidId>e826da1b-b193-4030-ad13-8798617d1000</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='business_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;business_name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a826792b-3467-4493-9e46-02a27587cbd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>80a4bd55-3ed6-4397-b10d-b25e1948b447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>business_name</value>
      <webElementGuid>d3cccc43-becd-4195-932f-65421c41a112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>business_name input mb1</value>
      <webElementGuid>f8c8613b-5d8a-4ed5-9b45-7706b476b59d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Business Name</value>
      <webElementGuid>bd3d814a-30d3-4e17-9b90-c534736c8aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/section[@class=&quot;grey-box mt1&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;demo_form bgb br8 p3&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 form-group&quot;]/div[1]/div[@class=&quot;form&quot;]/input[@class=&quot;business_name input mb1&quot;]</value>
      <webElementGuid>c464743c-a735-47f9-8aaf-b54151328bd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='business_name']</value>
      <webElementGuid>1ca66dd1-b0e3-45a9-affa-d70b1c3235bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/section/div/div/div[2]/div/div/div/div/div/div/div/div/input[3]</value>
      <webElementGuid>e2baf4c7-56e9-4f64-a9de-bbf439f0e8e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>44d7f420-a45b-46c2-b472-1e59b311316e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'business_name' and @placeholder = 'Business Name']</value>
      <webElementGuid>4e2d74fc-9f29-42dc-86f3-5b4e0058f364</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
